export default [
    {id: 1,
    quote:'Dream big and dare to fail.',
    author:'Norman Vaughan'},
    {id: 2,
    quote:'If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough.',
    author:'Oprah Winfrey'},
    {id: 3,
    quote: "Eighty percent of success is showing up.",
    author:'Woody Allen'},
    {id: 4,
    quote: "The battles that count aren’t the ones for gold medals. The struggles within yourself–the invisible battles inside all of us–that’s where it’s at.",
    author: "Jesse Owens"},
    {id: 5,
    quote: "I didn’t fail the test. I just found 100 ways to do it wrong.",
    author: "Benjamin Franklin"},
    {id: 6,
    quote: "The two most important days in your life are the day you are born and the day you find out why.",
    author: "Mark Twain"},
    {id: 7,
    quote: "An unexamined life is not worth living.",
    author: "Socrates"},
    {id: 8,
    quote: "If you want to lift yourself up, lift up someone else.",
    author: "Booker T. Washington"},
    {id: 9,
    quote: "Remember no one can make you feel inferior without your consent.",
    author: "Eleanor Roosevelt"},
    {id: 10,
    quote: "Happiness is not something readymade. It comes from your own actions.",
    author: "Dalai Lama"},
    {id: 11,
    quote: "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.",
    author: "Erma Bombeck"},
    {id: 12,
    quote: "If you want your children to turn out well, spend twice as much time with them, and half as much money.",
    author: "Abigail Van Buren"},
    {id: 13,
    quote: "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.",
    author: "Jesus"},
    
]